version: '3.4'

services:
  helloworld:
    image: helloworld
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command: -c "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 80"
    ports:
      - 80
      - 5678:5678
    environment:
      - FLASK_APP=app.py
